### ISSUE TITLE
Not compatible with Inkdrop v.4.5.0

### ISSUE THREAD

**Issue by tuang3142** [notapianokey/inkdrop-insert-date#1]
```
$ ipm install insert-date
Installing insert-date to /Users/user/Library/Application Support/inkdrop/packages ✗
No available version compatible with the installed Inkdrop version: 4.5.0
```
I am using macOS Catalina (10.15.2)

**Comment by smesterheide** [comment]
Sorry, but the plugin was written for Inkdrop version 3 and I am not planning to update it.

Feel free to fork the repo and adjust the `engines` property in `package.json`. With some luck the plugin might still run.

**Comment by tuang3142** [comment]
Ok. Happy to dev this. 
I am transitioning from Notion. It has a really cool feature where you can type `@Today` to insert the current date.

**Comment by craftzdog** [comment]
Hi @sambrezo.
Would you please update it, as I provided you a plugin developer license?

Here is the migration guide: https://docs.inkdrop.app/manual/plugin-migration-from-v3-to-v4

**Comment by craftzdog** [comment]
I took it over as an official plugin here: https://my.inkdrop.app/plugins/insert-date
You can close this issue.
Thanks!
